### ISSUE TITLE
Build fails on Ubuntu 18.04LTS

### ISSUE THREAD

**Issue by caroline-lin** [dilevin/DGPCompFab#1]
Oh no!

After manually installing cling, I ran

`cmake .. -DCMAKE_BUILD_TYPE=RELEASE`

from my_project_directory/DGP_Comp_Fab/A1/build.

I got this error:

> CMake Error at /home/caroline/recurse/graphics/DGPCompFab/interpreter/CMakeLists.txt:25 (find_package):
>   By not providing "FindClang.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "Clang", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "Clang" with any of
>   the following names:
> 
>     ClangConfig.cmake
>     clang-config.cmake
> 
>   Add the installation prefix of "Clang" to CMAKE_PREFIX_PATH or set
>   "Clang_DIR" to a directory containing one of the above files.  If "Clang"
>   provides a separate development package or SDK, be sure it has been
>   installed.

If I comment out line 25 of `interpreter/CMakeLists.txt` ( the find_package(Clang REQUIRED) ) I get the same error, but with Cling instead of Clang, at line 71 of the same CMakeLists.txt. 

If I comment out both find_package lines, CMake completes successfully, but the generated Makefile fails to compile the assignment.

Some error logs:
[CMakeError.log](https://github.com/dilevin/DGPCompFab/files/2383594/CMakeError.log)
[CMakeOutput.log](https://github.com/dilevin/DGPCompFab/files/2383595/CMakeOutput.log)

**Comment by dilevin** [comment]
HI Caroline, 

Can you check that you the clang cmake directory exists in the ThirdParty directory. For instance on my machine it lives here:  ./AssignmentDirectory/ThirdParty/src/build/install/lib/cmake/clang

ClangConfig should be in this directory.

-Dave

**Comment by FreakingBarbarians** [comment]
I had the same issue. My build from cling was in the same directory as the src.
/ThirdParty/build
/ThirdParty/src
I moved the build into the src and it worked fine for me.

Alternatively you can hunt the files down yourself and add the absolute paths to the CMakeLists.txt in the src for A1 in this line

"set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} ${PROJECT_SOURCE_DIR}/../ThirdParty/libigl/external/eigen **[add the paths here without "[]" separated by whitespace]** CACHE PATH "Root include directory for Eigen3" FORCE) 
set(CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/../cmake CACHE PATH "Root include directory for Eigen3" FORCE)"

**Comment by dilevin** [comment]
Thanks to the early beta testers! I made a couple of changes to the code to fix build bugs so please pull the latest version. 

1. As mentioned above by @FreakingBarbrians, you need to make sure that the build directory for cling is in `{SRC_DIRECTORY}/ThirdParty/src/build `

2. The current version of libfive will complain about the method isnan. To fix this, open the file:ThirdParty/libfive/libfive/src/eval/eval_interval.cpp and replace `isnan` with `std::isnan`

**Comment by caroline-lin** [comment]
Update: build and demo work, hurray!

Re: 1. Oops, my problem earlier was actually caused by forgetting to run `make install` as the final step for building cling (my ./install directory was missing).

For other linux/make users: it might be helpful to change the last two instructions in the cling manual install: from

>>> mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=[Install Path] -DCMAKE_BUILD_TYPE=[Build configuration, e.g. Release or Debug] ..\src
cmake --build .
cmake --build . --target install

Replace the last two lines with
make -j4 
make -j4 install
(I use 4 because I have 4 threads on my laptop). This speeds up the build time significantly since the cmake interface runs make in single-threaded mode...
