### ISSUE TITLE
squared_edge_lengths.h: Error: Simplex size (0) not supported

### ISSUE THREAD

**Issue by Emilyeyang** [dilevin/DGPCompFab#12]
When I recompiled my file to test the gradient descent method, this showed up on my terminal, what does this mean?

squared_edge_lengths.h: Error: Simplex size (0) not supported

Also, what kind of value does std::cout in the comment line give you? Is it running time or the return value of a function?

**Comment by dilevin** [comment]
This means that no mesh was generated. It usually means there is a bug in your gradient descent code. When you run the code without optimization it should generate a rectangular bar.
