### ISSUE TITLE
Building A3

### ISSUE THREAD

**Issue by Emilyeyang** [dilevin/DGPCompFab#15]
I have two questions:
1.When I tried to update the content of githut, it always give me this error:

MacBook-Pro-2:build emilyyang$ git pull origin master 
fatal: Couldn't find remote ref master 

2.When I tried to build A3 file, this happened:
 
MacBook-Pro-2:build emilyyang$ make -j8
make: *** No targets specified and no makefile found.  Stop.

What caused these problems?

**Comment by dilevin** [comment]
I just tried this (run from my {SRC_DIRECTORY} and it works as expected on my machine. Have you tried again, is this still a problem ?

**Comment by dilevin** [comment]
Just to clarify
1. Have you managed to pull the updated project from the git repo ? If `git pull origin master` continues to fail, please try cloning the the assignment repo into a new directory. I've tried this several times now and it always works on my machine

2. This error arises when you don't run cmake for the assignment. Make sure you follow the installation instructions for each assignment which I've summarized below:
  a. create an  A3/build directory
  b.`cd build` then `cmake .. -DCMAKE_BUILD_TYPE=Release` 
  c. Then run `make all -j8`.

**Comment by Emilyeyang** [comment]
For the second one, I did exactly what the instruction said.

For the first one, I tried to delete the whole A3 folder and update it from the website by using: 
git pull origin master. But it shows the information below:

MacBook-Pro-2:{SRC_DIRECTORY} emilyyang$ git checkout master
M	A1/scripts/testScript.cpp
M	A1/scripts/union.cpp
D	A2/A2.pdf
M	A2/include/Optimization.h
M	A2/scripts/robotArm.cpp
M	A2/src/Optimization.inl
D	A3/A3.pdf
D	A3/CMakeLists.txt
D	A3/include/ForceSpringA3.h
D	A3/include/TimeStepperEulerImplicitLinearA3.h
D	A3/src/main.cpp
M	ThirdParty/libfive
M	ThirdParty/libigl
D	slides/01-Intro.pdf
D	slides/02-Modelling-ilovepdf-compressed.pdf
D	slides/03-Optimization-compressed.pdf
D	slides/04-Simulation I-compressed.pdf
M	util/include/csgOps.h
M	util/src/csgOps.cpp
M	util/src/shapes.cpp
Already on 'master'
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

MacBook-Pro-2:{SRC_DIRECTORY} emilyyang$ git pull origin master
From https://github.com/dilevin/DGPCompFab
 * branch            master     -> FETCH_HEAD
Already up to date.

But my A3 folder is not there.

**Comment by dilevin** [comment]
Your git output shows that the A3 folder created and contained all the necessary files but you deleted it. `git pull origin master` will not fix this.

The easiest way around this is to clone the whole repository into a new directory. i.e run:
`git clone --recursive https://github.com/dilevin/DGPCompFab.git ./DGPCompFab`

This will redownload all the project folders including A3.
