### ISSUE TITLE
Missing libfive-guile

### ISSUE THREAD

**Issue by FreakingBarbarians** [dilevin/DGPCompFab#16]
When I try to build I get this error.
```
Checking dependencies:
  libfive: ✓
  libfive-guile:     ✘   (needs Guile 2.2 or later)
  Studio:       ✘   (needs Guile 2.2 or later)
-- Configuring incomplete, errors occurred!
```

Am I missing something? Or is the repo missing guile?

**Comment by dilevin** [comment]
This check is not an error

It’s done by Lib five. If qt and guile are not installed, only the lib five library is built which is the desired outcome.

**Comment by FreakingBarbarians** [comment]
Installing guile separately fixed this issue.

I'm on mac so I just installed using homebrew

https://github.com/libfive/libfive/tree/d9033dfb4bc7d7c1aabe9789157acb9bea8b9fdd

I then ran into this issue (which was the true problem)

```
CMake Error at CMakeLists.txt:60 (add_subdirectory):
  The source directory

    /Users/.../Desktop/DGPCompFab/ThirdParty/Gauss

  does not contain a CMakeLists.txt file.
```

Because when I pulled I did not init the new submodule GAUSS

running 

```
git submodule update --recursive --init
```

fixed this problem.
