### ISSUE TITLE
Incorrect Path to archbridge mesh

### ISSUE THREAD

**Issue by FreakingBarbarians** [dilevin/DGPCompFab#17]
In main.cpp

```
igl::readMESH("/Users/dilevin/Documents/Teaching/CompFabUofT/2018b/Instructor/ThirdParty/GAUSS/data/meshesTetWild/archbridge.mesh", V,T,F);
```
This path does not exist (unless I'm secretly David), causing a segfault.

I changed to.

```
igl::readMESH(dataDir() + "/meshesTetWild/archbridge.mesh", V,T,F);
```

Which is the same mesh as in A2.

The mesh loads now. Bridge comes up as completely blue but I think that's because I haven't implemented anything else yet :)

**Comment by dilevin** [comment]
Thanks for catching this. I lazily hard coded the path. Can you make a pull request with this change please ? 

Dave

**Comment by FreakingBarbarians** [comment]
Working on getting a patch. But I think the update to libigl messed up my git repo. Trying to fix it now :(
