### ISSUE TITLE
what is the x in the phi function?

### ISSUE THREAD

**Issue by Emilyeyang** [dilevin/DGPCompFab#19]
The function *double phi(double x) { ... } returns the value of the linear shape function
$\lambda_{VERTEX}$, evaluated at $\mathbf{x}$.

In the given document, for example,
\lambda_1=\frac{(y_2-y_3)(x-x_3)+(x_3-x_2)(y-y_3)}{\det(T)}=\frac{(y_2-y_3)(x-x_3)+(x_3-x_2)(y-y_3)}{(y_2-y_3)(x_1-x_3)+(x_3-x_2)(y_1-y_3)}\, 
this means, we need all the (x,y,z) values of 4 points in order to calculate lambda. But we only have one  value x  as an input. what does this x represent?

**Comment by dilevin** [comment]
the function takes double *x, not double x as an input.

double *x is a 3d array that stores the x,y,z positions of a point, x, in  world space. 

i.e x[0] = x, x[1] = y, x[2] = z.

**Comment by Emilyeyang** [comment]
Thank you for that explanation. What about qdofs and qdotdofs? What values do they represent? Because I need x1=(x1,y1,z1), x2=(x2,y2,z2), x3=(x3,y3,z3) and x4=(x4,y4,z4) to calculate each lambda but I am not sure which one of those two variables it is.

**Comment by dilevin** [comment]
1. q's are the 3D displacements of each node in the tetrahedra 
2. You are integrating the the stiffness matrix over the tetrahedra. The stiffness matrix is made of up derivatives of a linear function.  You should be able to find an very easy way to integrate a function of this form.

**Comment by Emilyeyang** [comment]
Yes, I know that we can simply multiply the volume to the single stiffness matrix. But volume() is not imported to the QudraticLinear.h , can we just import that to QudraticLinear.h by ourself?
Also, I have the same question for dphi, in order to call that function, we need x, but there is no x in QudraticLinear.h, then how can I call this function?
