### ISSUE TITLE
couldn't run ComFabA4

### ISSUE THREAD

**Issue by Emilyeyang** [dilevin/DGPCompFab#20]
When I was trying to run the bridge on A4, terminal gave me such an error:

IOError: /Users/dilevin/Documents/Teaching/CompFabUofT/2018b/Instructor/ThirdParty/GAUSS/data/meshesTetWild/archbridge.mesh could not be opened...Segmentation fault: 11

What does this error mean?

**Comment by FreakingBarbarians** [comment]
Re-pull, it's an error I fixed and it's been merged.

There's a hard coded path in the older version of the assignment.

**Comment by Emilyeyang** [comment]
Thank you, it worked.
