### ISSUE TITLE
Matlab License error on CDF

### ISSUE THREAD

**Issue by FreakingBarbarians** [dilevin/DGPCompFab#26]
When I try to run the example mechanism I get this error 

```
License checkout failed.
License Manager Error -18
Make sure the license file on the MATLAB client matches the license file of the license
server and that the license server has been started properly.

Troubleshoot this issue by visiting:
http://www.mathworks.com/support/lme/R2016a/18

Diagnostic Information:
Feature: Optimization_Toolbox
License path: 27000@licsrv.teach.cs.toronto.edu:27000:@licsrv.teach.cs.toronto.edu
Licensing error: -18,147.

Error in linkage (line 176)
    opt = optimoptions('lsqnonlin',...
```

I'm running matlab on cdf. I'm guessing the license for cdf doesn't contain the optimization toolbox? Or maybe something else is weird.

**Comment by dilevin** [comment]
If the cdf machines don’t have the right toolboxes you can download a free trial of matlab from the math works website

**Comment by FreakingBarbarians** [comment]
I got my trial working. It seems like I'll have to use their web interface (yuck). Thanks! :)
