### ISSUE TITLE
building A2

### ISSUE THREAD

**Issue by Emilyeyang** [dilevin/DGPCompFab#7]
When I was running code 'make -j8', this error occurred and my file could not be build properly.

[ 19%] Building CXX object imgui/CMakeFiles/imgui.dir/imgui_impl_glfw_gl3.cpp.o
/Users/emilyyang/{SRC_DIRECTORY}/ThirdParty/libigl/external/imgui/imgui_impl_glfw_gl3.cpp:391:16: error: no member named 'WantMoveMouse' in 'ImGuiIO'
        if (io.WantMoveMouse)
            ~~ ^
/Users/emilyyang/{SRC_DIRECTORY}/ThirdParty/libigl/external/imgui/imgui_impl_glfw_gl3.cpp:419:12: error: no member named 'NavFlags' in 'ImGuiIO'
    if (io.NavFlags & ImGuiNavFlags_EnableGamepad)
        ~~ ^
/Users/emilyyang/{SRC_DIRECTORY}/ThirdParty/libigl/external/imgui/imgui_impl_glfw_gl3.cpp:419:23: error: use of undeclared identifier 'ImGuiNavFlags_EnableGamepad'; did you mean 'ImGuiConfigFlags_NavEnableGamepad'?
    if (io.NavFlags & ImGuiNavFlags_EnableGamepad)
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      ImGuiConfigFlags_NavEnableGamepad
/Users/emilyyang/{SRC_DIRECTORY}/ThirdParty/libigl/external/imgui/imgui/imgui.h:856:5: note: 
      'ImGuiConfigFlags_NavEnableGamepad' declared here
    ImGuiConfigFlags_NavEnableGamepad       = 1 << 1,   // Master gamepad navigation enable flag. This ...
    ^
3 errors generated.
make[2]: *** [imgui/CMakeFiles/imgui.dir/imgui_impl_glfw_gl3.cpp.o] Error 1
make[1]: *** [imgui/CMakeFiles/imgui.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

[ 56%] Built target five
make: *** [all] Error 2

Do I lack some file?

**Comment by dilevin** [comment]
To fix this you need to do two things. 

First `cd {SRC_DIRECTORY}/ThirdParty/libigl` and run `git checkout 0dd9528`

Second `cd {SRC_DIRECTORY}/ThirdParty/libigl/external/imgui/imgui` and run `git checkout 7cc1bc7`

**Comment by Emilyeyang** [comment]
Thank you, it worked now.
