### ISSUE TITLE
A1 Source Code Submission

### ISSUE THREAD

**Issue by elaine-huynh** [dilevin/DGPCompFab#8]
Could you please clarify which source files we should submit for A1? Do you just want the files we added/modified:

- $SRC/util/src/csgOps.cpp
- $SRC/A1/scripts/model.cpp (or whatever we named the script for our parametric model)

Or is there a particular list of directories/files you'd like us to include in the zip file?

Thanks in advance!

**Comment by dilevin** [comment]
Sure, that's fine.
